# Read the documentation on how to configure charted-server:
# https://charts.noelware.org/docs/server/configuration

postgres: {}
metrics: true
debug: true
redis: {}
storage:
  filesystem:
    directory: /var/lib/noelware/charted/server/data
