# 🐻‍❄️📦 charted-server: Free, open source, and reliable Helm Chart registry made in Rust
# Copyright 2022-2024 Noelware, LLC. <team@noelware.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[workspace]
resolver = "2"
members = ["proc-macros", "tools/devtools", "tools/helm-plugin"]

[workspace.package]
documentation = "https://charts.noelware.org/docs"
edition = "2021"
homepage = "https://charts.noelware.org"
license = "Apache-2.0"
publish = false
repository = "https://github.com/charted-dev/charted"
authors = [
    "Noel Towa <cutie@floofy.dev>",
    "Spotlight <spotlight@joscomputing.space>",
    "Noelware, LLC. <team@noelware.org>",
]

[workspace.dependencies]
async-trait = "0.1.77"
color-eyre = { version = "0.6.2", features = ["issue-url", "tracing-error"] }
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.17", features = ["derive", "env"] }
clap_complete = "4.4.7"
dotenvy = "0.15.7"
semver = { version = "1.0.21", features = ["serde"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
eyre = "0.6.11"
which = "5.0.0"

[package]
name = "charted"
description = "🐻‍❄️📦 Free, open source, and reliable Helm Chart registry made in Rust"
version = "0.1.0-beta"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "charted"
path = "./src/bin/main.rs"

[dependencies]
argon2 = "0.5.2"
async-recursion = "1.0.5"
async-trait.workspace = true
aws-sdk-s3 = "1.12.0"
axum = { version = "0.7.4", features = ["http2", "multipart"] }
axum-server = { version = "0.6.0", features = ["tls-openssl"] }
azure_storage = "0.19.0"
base64 = "0.21.7"
charted-proc-macros = { version = "0.0.0-devel.0", path = "proc-macros" }
chrono.workspace = true
clap.workspace = true
clap_complete.workspace = true
cli-table = "0.4.7"
color-eyre.workspace = true
cron = "0.12.0"
dotenvy.workspace = true
elasticsearch = "8.5.0-alpha.1"
erased-serde = "0.4.2"
eyre.workspace = true
flate2 = "1.0.28"
futures-util = "0.3.30"
hex = "0.4.3"
humantime = "2.1.0"
iterutils = "0.1.0"
jsonwebtoken = "9.2.0"
ldap3 = "0.11.3"
md-5 = "0.10.6"
meilisearch-sdk = "0.24.3"
mimalloc = "0.1.39"
mime = "0.3.17"
moka = { version = "0.12.3", features = ["future"] }
multer = "3.0.0"
noelware-config = { git = "https://github.com/Noelware/core-rs", version = "0.1.0", rev = "41257fc1eb6d89a4b4c42a1a2727fd13814ff9d0", features = [
    "derive",
] }
noelware-log = { git = "https://github.com/Noelware/core-rs", version = "0.1.0", rev = "41257fc1eb6d89a4b4c42a1a2727fd13814ff9d0", features = [
    "log",
] }
noelware-remi = { git = "https://github.com/Noelware/core-rs", version = "0.1.0", rev = "41257fc1eb6d89a4b4c42a1a2727fd13814ff9d0", features = [
    "azure",
    "fs",
    "s3",
] }
noelware-serde = { git = "https://github.com/Noelware/core-rs", version = "0.1.0", rev = "41257fc1eb6d89a4b4c42a1a2727fd13814ff9d0", features = [
    "tracing",
] }
num_cpus = "1.16.0"
once_cell = "1.19.0"
openssl = "0.10.62"
owo-colors = { version = "4.0.0", features = ["supports-color"] }
paste = "1.0.14"
prometheus-client = "0.22.0"
promptly = "0.3.1"
prost = "0.12.3"
prost-types = "0.12.3"
rand = "0.8.5"
redis = { version = "0.24.0", features = [
    "sentinel",
    "tokio-comp",
    "connection-manager",
] }
regex = "1.10.2"
remi = "0.5.0"
remi-azure = { version = "0.5.0", features = ["serde", "tracing"] }
remi-fs = { version = "0.5.0", features = ["serde", "tracing"] }
remi-s3 = { version = "0.5.0", features = ["serde", "tracing"] }
reqwest = "0.11.23"
rust-embed = "8.2.0"
semver.workspace = true
sentry = "0.32.1"
sentry-eyre = "0.1.0"
sentry-tower = "0.32.1"
sentry-tracing = "0.32.1"
serde.workspace = true
serde_json.workspace = true
serde_repr = "0.1.18"
serde_yaml = "0.9.30"
sqlx = { version = "0.7.3", features = [
    "postgres",
    "runtime-tokio",
    "tls-native-tls",
    "chrono",
] }
tar = "0.4.40"
tokio = { version = "1.35.1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "io-util",
    "fs",
    "signal",
] }
tokio-util = "0.7.10"
tonic = "0.10.2"
tower = "0.4.13"
tower-http = { version = "0.5.1", features = [
    "compression-full",
    "auth",
    "cors",
    "catch-panic",
    "limit",
] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-log = "0.2.0"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = "0.3.18"
ubyte = { version = "0.10.4", features = ["serde"] }
utoipa = { version = "4.2.0", features = ["uuid"] }
uuid = { version = "1.6.1", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }

[build-dependencies]
chrono = "0.4.31"
rustc_version = "0.4.0"
tonic-build = "0.10.2"
which.workspace = true

[dev-dependencies]
remi-fs = "0.5.0"
tempfile = "3.9.0"
tokio = "1.35.1"

[profile.dev]
incremental = false

[profile.release]
codegen-units = 1
incremental = true
opt-level = "z"
strip = true
lto = true
