#!/usr/bin/env bash

# 🐻‍❄️📦 charted-server: Free, open source, and reliable Helm Chart registry made in Rust
# Copyright 2022-2024 Noelware, LLC. <team@noelware.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o pipefail

function devtools::log {
    echo "[dev] $*"
}

function devtools::fatal {
    echo "[dev][failure] $*"
    exit 1
}

BASH_SRC=${BASH_SOURCE[0]}
while [ -L "$BASH_SRC" ]; do
    target=$(readlink "$BASH_SRC")
    if [[ $target == /* ]]; then
        BASH_SRC=$target
    else
        dir=$(dirname "$BASH_SRC")
        BASH_SRC=$dir/$target
    fi
done

SCRIPT_DIR=$(cd -P "$(dirname $BASH_SRC)" >/dev/null 2>&1 && pwd)
! [ -d "$SCRIPT_DIR/.cache" ] && mkdir "$SCRIPT_DIR/.cache"

CARGO=${CARGO:-cargo}
BAZEL_ARGS=${CARGO_ARGS:-}
REBUILD=${DEV_REBUILD:-}

if [[ "x$CARGO" == "xcargo" ]] && ! command -v cargo >/dev/null; then
    devtools::fatal "Unable to find \`cargo\` installed! Did you install \`rustup\`?"
fi

if ! [[ -f "$SCRIPT_DIR/.cache/dev" || "x$REBUILD" != "x" ]]; then
    [[ "x$REBUILD" != "x" && -f "$SCRIPT_DIR/.cache/dev" ]] && rm -rf "$SCRIPT_DIR/.cache/dev"

    devtools::log "Compiling \`charted-devtools\` binary!"
    devtools::log "$ $CARGO build --release $CARGO_ARGS --bin charted-devtools"

    "$CARGO" build --release $CARGO_ARGS --bin charted-devtools
    cp $SCRIPT_DIR/target/release/charted-devtools $SCRIPT_DIR/.cache/dev
fi

devtools::log "$ ./dev $*"
"$SCRIPT_DIR/.cache/dev" $*
