DROP TABLE IF EXISTS "repository_members";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "organizations";
DROP TABLE IF EXISTS "user_connections";
DROP TABLE IF EXISTS "repositories";
DROP TABLE IF EXISTS "api_keys";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "organization_members";
DROP TABLE IF EXISTS "repository_releases";
