#!/usr/bin/env node

/*
 * 📦 charted-server: Free, open source, and reliable Helm Chart registry made in Kotlin.
 * Copyright 2022 Noelware <team@noelware.org>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// @ts-check

const { promisify } = require('util');
const { spawn } = require('child_process');

const scriptPath = process.argv.slice(2);
if (scriptPath.length === 0) throw new Error('Missing script path to execute');

const spawnAsync = promisify(spawn);
spawnAsync(
  'node',
  [
    '--no-warnings',
    '--no-deprecation',
    '--experimental-specifier-resolution=node',
    '--loader=ts-node/esm/transpile-only',
    scriptPath[0]
  ],
  {
    windowsHide: true,
    stdio: 'inherit',
    env: {
      TS_NODE_PROJECT: './scripts/tsconfig.json'
    }
  }
);
