/*
 * 📦 charted-server: Free, open source, and reliable Helm Chart registry made in Kotlin.
 * Copyright 2022-2023 Noelware <team@noelware.org>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.noelware.charted.tools.kotlin.rust

import org.noelware.charted.databases.postgres.models.*
import org.noelware.charted.types.helm.RepoType
import java.io.File
import kotlin.system.exitProcess

fun main(args: Array<String>) {
    if (args.isEmpty()) {
        println("Missing argument: FILE")
        exitProcess(1)
    }

    val stubFile = File(args[0])
    if (!stubFile.exists()) stubFile.createNewFile()

    val actualResult = buildString {
        appendLine(
            """
        |// 📦 charted-server: Free, open source, and reliable Helm Chart registry made in Kotlin.
        |// Copyright 2022-2023 Noelware <team@noelware.org>
        |//
        |// Licensed under the Apache License, Version 2.0 (the "License");
        |// you may not use this file except in compliance with the License.
        |// You may obtain a copy of the License at
        |//
        |//    http://www.apache.org/licenses/LICENSE-2.0
        |//
        |// Unless required by applicable law or agreed to in writing, software
        |// distributed under the License is distributed on an "AS IS" BASIS,
        |// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        |// See the License for the specific language governing permissions and
        |// limitations under the License.
        |
        |#[allow(clippy::all)]
        |
        |// This file was auto-generated by the `./tools/kt-to-rust` tool. Please do not edit this file,
        |// and instead run `./gradlew :tools:kt-to-rust:run` to update this file!
            """.trimMargin()
        )

        appendLine()
        appendLine(Generator.generate(RepoType::class))
        appendLine(Generator.generate(ApiKeys::class))
        appendLine(Generator.generate(OrganizationMember::class))
        appendLine(Generator.generate(Organization::class))
        appendLine(Generator.generate(Repository::class))
        appendLine(Generator.generate(RepositoryMember::class))
        appendLine(Generator.generate(RepositoryRelease::class))
        append(Generator.generate(User::class))
    }

    stubFile.writeBytes(actualResult.toByteArray())
}
