#!/usr/bin/env bash

# 🐻‍❄️📦 charted-server: Free, open source, and reliable Helm Chart registry made in Rust
# Copyright 2022-2025 Noelware, LLC. <team@noelware.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

source "$(cd "$(dirname $0)/.." && pwd)/_shared.sh"

buildflags=${BUILDFLAGS:-}
root=$(cd "$(dirname $0)/../.." && pwd)
cargo=${CARGO:-cargo}
rustflags=${RUSTFLAGS:-}

build() {
    if ! command -v "$cargo" >/dev/null; then
        echo "~> Missing \`cargo\` binary (defined from \`\$CARGO\`: $cargo)"
        exit 1
    fi

    local bin="$1"
    arch="unknown"

    if noelware::arch::x86_64; then
        arch="x86_64"
    elif noelware::arch::aarch64; then
        arch="aarch64"
    fi

    [ "$arch" == "unknown" ] && {
        echo "~> unable to determine architecture; cannot run build"
        exit 1
    }
}

# noelware::startGroup ""
# main
# noelware::endGroup
