#!/bin/bash

echo "[::charted-server] Checking Spotless..."

./gradlew spotlessCheck
if [[ "$?" != "0" ]]; then
  echo "[::charted-server] Run \`make spotless\` and commit again."
  exit $?
fi

./gradlew :build-tools:spotlessCheck
if [[ "$?" != "0" ]]; then
  echo "[::charted-server] Run \`make spotless\` and commit again."
  exit $?
fi

echo "[::charted-server] 👍 Everything seems ok!"
