#!/bin/bash

# 📦 charted-server: Free, open source, and reliable Helm Chart registry made in Kotlin.
# Copyright 2022 Noelware <team@noelware.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SKIP_SPOTLESS=${SKIP_SPOTLESS:-}

if [[ "x$SKIP_SPOTLESS" != "x" ]]; then
    echo "🐻‍❄️🪄 [precommit-hook] Skipping precommit hook since \`SKIP_SPOTLESS\` was defined."
    exit 0
fi

echo "🐻‍❄️🪄 [precommit-hook] Running Spotless..."
./gradlew spotlessCheck

if [[ "$?" != "0" ]]; then
  echo "🐻‍❄️🪄 [precommit-hook] Spotless was not ran (and there is linting errors), please run \`make spotless\`"
  exit 1
else
  echo "🐻‍❄️🪄 [precommit-hook] Everything is ok! :3"
fi
