# 📦 charted-server: Free, open source, and reliable Helm Chart registry made in Kotlin.
# Copyright 2022 Noelware <team@noelware.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

project_name: cassandra-migrations
before:
  hooks:
    - go mod tidy
    - go mod download
env:
  - CGO_ENABLED=0
  - GO11MODULE=on
builds:
  - id: cassandra-migrations
    binary: cassandra-migrations
    ldflags:
    - -s -w
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
    - arm64
    - "386"
    - arm
    goarm:
    - "6"
    - "7"
    ignore:
    - goos: windows
      goarch: arm64
    - goos: windows
      goarm: "6"
    - goos: windows
      goarm: "7"
# dockers:
# - goarch: amd64
#   use: buildx
#   {{- if .Env.NIGHTLY }}
#   image_templates:
#     - ghcr.io/charted-dev/charted:nightly-amd64
#     - ghcr.io/charted-dev/charted:{{ .Version }}-nightly-amd64
#     - ghcr.io/charted-dev/charted:{{ .Major }}-nightly-amd64
#     - ghcr.io/charted-dev/charted:{{ .Major }}.{{ .Minor }}-nightly-amd64
#   {{- end }}
