#!/usr/bin/env bash

# 🐻‍❄️📦 charted-server: Free, open source, and reliable Helm Chart registry made in Rust
# Copyright 2022-2025 Noelware, LLC. <team@noelware.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The ./hack/generate-migration/sqlite script allows to generate migrations
# for SQLite usage. This is meant to not repeat the following command:
#
#     charted ~ crates/database $> DATABASE_URL="postgresql://..." diesel migration generate "..." --migration-dir ./migrations/postgresql

dir="$(realpath "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/../..")"
additionalargs=(
    "--config-file=./diesel.postgresql.toml"
)

[ -f "$dir/.env" ] && export $(grep -v '^#' .env | xargs)

if ! command -v diesel >/dev/null; then
    echo "error: missing \`diesel\` command. use \`cargo install diesel --features \"sqlite postgresql\"\` to install it."
    exit 1
fi

if ! [ -n "${DATABASE_URL}" ]; then
    echo "error: missing \`DATABASE_URL\` environment variable; please set \`DATABASE_URL\`"
    exit 1
fi

# Go into the `crates/database` directory.
pushd "$dir/crates/database" >/dev/null

echo "$ diesel $@ ${additionalargs[@]}"
diesel $@ ${additionalargs[@]}

popd >/dev/null
