# 📦 charted-server: Free, open source, and reliable Helm Chart registry made in Kotlin.
# Copyright 2022-2023 Noelware <team@noelware.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Nightly Release Pipeline
on:
  release:
    types: [prereleased]
permissions:
  contents: write
  packages: write
jobs:
  archives:
    name: Build and publish archive [${{matrix.tasks.prettyName}}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tasks:
          - { ext: "deb",    task: "buildDebRepo", project: ":distribution:deb", prettyName: "Deb", buildDir: "./distribution/deb/build" }
          - { ext: "rpm",    task: "buildRpmRepo", project: ":distribution:rpm", prettyName: "Rpm", buildDir: "./distribution/rpm/build" }
          - { ext: "tar.gz", task: "distTar",      project: ":cli",              prettyName: "Tar", buildDir: "./cli/build" }
          - { ext: "zip",    task: "distZip",      project: ":cli",              prettyName: "Zip", buildDir: "./cli/build" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get current release tag
        uses: auguwu/git-tag-action@master
        id: tag

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Lint code-base with Spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck --no-daemon --scan

      - name: Compiles Kotlin source sets
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileKotlin --no-daemon --scan

      - name: Compiles Java source sets
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileJava --no-daemon --scan

      - name: Run unit and integration tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --no-daemon --scan

      - name: Build ${{matrix.tasks.prettyName}} artifact
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{matrix.tasks.project}}:${{matrix.tasks.task}} --no-daemon --scan

      - name: Upload ${{matrix.tasks.prettyName}} artifact to workflow
        uses: actions/upload-workflow@v3
        with:
          name: charted-server.${{matrix.tasks.ext}}
          path: ${{matrix.tasks.buildDir}}/distributions/charted-server.${{matrix.tasks.ext}}

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{matrix.tasks.buildDir}}/distributions/charted-server.${{matrix.tasks.ext}}

      - name: Upload artifacts to Noelware's Artifact Registry
        uses: Noelware/s3-action@2.0.0
        with:
          files: ./cli/build/distributions/charted-server.${{matrix.tasks.ext}}
          path-format: $(prefix)/${{steps.tag.output.version}}/charted-server.${{matrix.tasks.ext}}
          access-key-id: ${{secrets.S3_ACCESS_KEY}}
          secret-key: ${{secrets.S3_SECRET_KEY}}
          endpoint: ${{secrets.S3_ENDPOINT}}
          prefix: /noelware/artifacts
          bucket: august
  docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get current release tag
        uses: auguwu/git-tag-action@master
        id: tag

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: charted-dev
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push! (x86_64)
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          context: .
          file: ./distribution/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/charted-dev/charted:${{steps.tag.outputs.version}}-amd64,
            ghcr.io/charted-dev/charted:latest-amd64

      - name: Build and push! (arm64)
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64/v8
          context: .
          file: ./distribution/docker/arm64.Dockerfile
          push: true
          tags: |
            ghcr.io/charted-dev/charted:${{steps.tag.outputs.version}}-arm64,
            ghcr.io/charted-dev/charted:latest-arm64

      - name: Create manifest image [:latest]
        uses: Noelware/docker-manifest-action@master
        with:
          base-image: ghcr.io/charted-dev/charted:latest
          push: true
          extra-images: |
            ghcr.io/charted-dev/charted:latest-amd64,
            ghcr.io/charted-dev/charted:latest-arm64

      - name: Create manifest image [:${{steps.tag.outputs.version}}]
        uses: Noelware/docker-manifest-action@master
        with:
          base-image: ghcr.io/charted-dev/charted:${{steps.tag.outputs.version}}
          push: true
          extra-images: |
            ghcr.io/charted-dev/charted:${{steps.tag.outputs.version}}-amd64,
            ghcr.io/charted-dev/charted:${{steps.tag.outputs.version}}-arm64
