/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/ui/AppShell.vue')['default']
    DropdownMenuRoot: typeof import('radix-vue')['DropdownMenuRoot']
    DropdownMenuTrigger: typeof import('radix-vue')['DropdownMenuTrigger']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    Navbar: typeof import('./src/components/ui/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/ui/shell/Sidebar.vue')['default']
    UserDropdown: typeof import('./src/components/ui/navbar/UserDropdown.vue')['default']
  }
}
